/*
 * generated by Xtext
 */
package org.xtext.example.mydsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {
	
	@Inject
	private MyDslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser createParser() {
		org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser result = new org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getType_declarationAccess().getAlternatives_1(), "rule__Type_declaration__Alternatives_1");
					put(grammarAccess.getField_declarationAccess().getAlternatives(), "rule__Field_declaration__Alternatives");
					put(grammarAccess.getField_declarationAccess().getAlternatives_0_1(), "rule__Field_declaration__Alternatives_0_1");
					put(grammarAccess.getMethod_declarationAccess().getAlternatives_7(), "rule__Method_declaration__Alternatives_7");
					put(grammarAccess.getParameterAccess().getAlternatives_2(), "rule__Parameter__Alternatives_2");
					put(grammarAccess.getVariable_declaratorAccess().getAlternatives_1(), "rule__Variable_declarator__Alternatives_1");
					put(grammarAccess.getVariable_initializerAccess().getAlternatives(), "rule__Variable_initializer__Alternatives");
					put(grammarAccess.getType_specifierAccess().getAlternatives(), "rule__Type_specifier__Alternatives");
					put(grammarAccess.getType_specifierAccess().getPrimitiveTypeAlternatives_0_0(), "rule__Type_specifier__PrimitiveTypeAlternatives_0_0");
					put(grammarAccess.getModifierAccess().getAlternatives(), "rule__Modifier__Alternatives");
					put(grammarAccess.getStatementAccess().getAlternatives(), "rule__Statement__Alternatives");
					put(grammarAccess.getFor_StatementAccess().getAlternatives_2(), "rule__For_Statement__Alternatives_2");
					put(grammarAccess.getExpressionAccess().getAlternatives(), "rule__Expression__Alternatives");
					put(grammarAccess.getExpression_auxAccess().getAlternatives(), "rule__Expression_aux__Alternatives");
					put(grammarAccess.getExpression_auxAccess().getSginAlternatives_5_0_0(), "rule__Expression_aux__SginAlternatives_5_0_0");
					put(grammarAccess.getExpression_auxAccess().getNumericSignAlternatives_6_0_0(), "rule__Expression_aux__NumericSignAlternatives_6_0_0");
					put(grammarAccess.getExpression_auxAccess().getTestingSignAlternatives_7_0_0(), "rule__Expression_aux__TestingSignAlternatives_7_0_0");
					put(grammarAccess.getExpression_auxAccess().getAlternatives_8_0(), "rule__Expression_aux__Alternatives_8_0");
					put(grammarAccess.getExpression_auxAccess().getLogicalSignAlternatives_8_0_0_0(), "rule__Expression_aux__LogicalSignAlternatives_8_0_0_0");
					put(grammarAccess.getExpression_auxAccess().getStringSignAlternatives_10_0_0(), "rule__Expression_aux__StringSignAlternatives_10_0_0");
					put(grammarAccess.getExpression_auxAccess().getBitSignAlternatives_11_0_0(), "rule__Expression_aux__BitSignAlternatives_11_0_0");
					put(grammarAccess.getExpression_auxAccess().getLogicOpAlternatives_12_0_0(), "rule__Expression_aux__LogicOpAlternatives_12_0_0");
					put(grammarAccess.getAmpersand_RuleAccess().getAlternatives_1(), "rule__Ampersand_Rule__Alternatives_1");
					put(grammarAccess.getLiteral_ExpressionAccess().getAlternatives(), "rule__Literal_Expression__Alternatives");
					put(grammarAccess.getLiteral_ExpressionAccess().getAlternatives_0(), "rule__Literal_Expression__Alternatives_0");
					put(grammarAccess.getCreating_ExpressionAccess().getAlternatives_1(), "rule__Creating_Expression__Alternatives_1");
					put(grammarAccess.getCreating_ExpressionAccess().getAlternatives_1_1_1(), "rule__Creating_Expression__Alternatives_1_1_1");
					put(grammarAccess.getCreating_ExpressionAccess().getAlternatives_1_1_2(), "rule__Creating_Expression__Alternatives_1_1_2");
					put(grammarAccess.getLogical_Expression_NRAccess().getAlternatives(), "rule__Logical_Expression_NR__Alternatives");
					put(grammarAccess.getLogical_Expression_NRAccess().getAlternatives_0_1(), "rule__Logical_Expression_NR__Alternatives_0_1");
					put(grammarAccess.getNumeric_Expression_NRAccess().getSinal_numericAlternatives_0_0(), "rule__Numeric_Expression_NR__Sinal_numericAlternatives_0_0");
					put(grammarAccess.getSwitch_statementAccess().getAlternatives_6(), "rule__Switch_statement__Alternatives_6");
					put(grammarAccess.getImport_statementAccess().getAlternatives_1(), "rule__Import_statement__Alternatives_1");
					put(grammarAccess.getCompilation_unitAccess().getGroup(), "rule__Compilation_unit__Group__0");
					put(grammarAccess.getType_declarationAccess().getGroup(), "rule__Type_declaration__Group__0");
					put(grammarAccess.getInterface_declarationAccess().getGroup(), "rule__Interface_declaration__Group__0");
					put(grammarAccess.getInterface_declarationAccess().getGroup_3(), "rule__Interface_declaration__Group_3__0");
					put(grammarAccess.getInterface_declarationAccess().getGroup_3_2(), "rule__Interface_declaration__Group_3_2__0");
					put(grammarAccess.getClass_declarationAccess().getGroup(), "rule__Class_declaration__Group__0");
					put(grammarAccess.getClass_declarationAccess().getGroup_3(), "rule__Class_declaration__Group_3__0");
					put(grammarAccess.getClass_declarationAccess().getGroup_4(), "rule__Class_declaration__Group_4__0");
					put(grammarAccess.getClass_declarationAccess().getGroup_4_2(), "rule__Class_declaration__Group_4_2__0");
					put(grammarAccess.getField_declarationAccess().getGroup_0(), "rule__Field_declaration__Group_0__0");
					put(grammarAccess.getField_declarationAccess().getGroup_2(), "rule__Field_declaration__Group_2__0");
					put(grammarAccess.getMethod_declarationAccess().getGroup(), "rule__Method_declaration__Group__0");
					put(grammarAccess.getMethod_declarationAccess().getGroup_6(), "rule__Method_declaration__Group_6__0");
					put(grammarAccess.getConstructor_declarationAccess().getGroup(), "rule__Constructor_declaration__Group__0");
					put(grammarAccess.getParameter_listAccess().getGroup(), "rule__Parameter_list__Group__0");
					put(grammarAccess.getParameter_listAccess().getGroup_1(), "rule__Parameter_list__Group_1__0");
					put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
					put(grammarAccess.getParameterAccess().getGroup_2_0(), "rule__Parameter__Group_2_0__0");
					put(grammarAccess.getVariable_declarationAccess().getGroup(), "rule__Variable_declaration__Group__0");
					put(grammarAccess.getVariable_declarationAccess().getGroup_3(), "rule__Variable_declaration__Group_3__0");
					put(grammarAccess.getVariable_declaratorAccess().getGroup(), "rule__Variable_declarator__Group__0");
					put(grammarAccess.getVariable_declaratorAccess().getGroup_1_0(), "rule__Variable_declarator__Group_1_0__0");
					put(grammarAccess.getVariable_declaratorAccess().getGroup_2(), "rule__Variable_declarator__Group_2__0");
					put(grammarAccess.getArray_initializerAccess().getGroup(), "rule__Array_initializer__Group__0");
					put(grammarAccess.getArray_initializerAccess().getGroup_2(), "rule__Array_initializer__Group_2__0");
					put(grammarAccess.getArray_initializerAccess().getGroup_2_1(), "rule__Array_initializer__Group_2_1__0");
					put(grammarAccess.getTypeAccess().getGroup(), "rule__Type__Group__0");
					put(grammarAccess.getStatic_initializerAccess().getGroup(), "rule__Static_initializer__Group__0");
					put(grammarAccess.getStatement_blockAccess().getGroup(), "rule__Statement_block__Group__0");
					put(grammarAccess.getStatementAccess().getGroup_1(), "rule__Statement__Group_1__0");
					put(grammarAccess.getStatementAccess().getGroup_7(), "rule__Statement__Group_7__0");
					put(grammarAccess.getStatementAccess().getGroup_8(), "rule__Statement__Group_8__0");
					put(grammarAccess.getStatementAccess().getGroup_9(), "rule__Statement__Group_9__0");
					put(grammarAccess.getStatementAccess().getGroup_12(), "rule__Statement__Group_12__0");
					put(grammarAccess.getStatementAccess().getGroup_13(), "rule__Statement__Group_13__0");
					put(grammarAccess.getStatementAccess().getGroup_14(), "rule__Statement__Group_14__0");
					put(grammarAccess.getStatementAccess().getGroup_15(), "rule__Statement__Group_15__0");
					put(grammarAccess.getFor_StatementAccess().getGroup(), "rule__For_Statement__Group__0");
					put(grammarAccess.getFor_StatementAccess().getGroup_2_2(), "rule__For_Statement__Group_2_2__0");
					put(grammarAccess.getExpressionAccess().getGroup_0(), "rule__Expression__Group_0__0");
					put(grammarAccess.getExpressionAccess().getGroup_0_0(), "rule__Expression__Group_0_0__0");
					put(grammarAccess.getExpressionAccess().getGroup_1(), "rule__Expression__Group_1__0");
					put(grammarAccess.getExpressionAccess().getGroup_2(), "rule__Expression__Group_2__0");
					put(grammarAccess.getExpressionAccess().getGroup_3(), "rule__Expression__Group_3__0");
					put(grammarAccess.getExpressionAccess().getGroup_3_0(), "rule__Expression__Group_3_0__0");
					put(grammarAccess.getExpressionAccess().getGroup_4(), "rule__Expression__Group_4__0");
					put(grammarAccess.getExpressionAccess().getGroup_4_0(), "rule__Expression__Group_4_0__0");
					put(grammarAccess.getExpressionAccess().getGroup_5(), "rule__Expression__Group_5__0");
					put(grammarAccess.getExpressionAccess().getGroup_6(), "rule__Expression__Group_6__0");
					put(grammarAccess.getExpressionAccess().getGroup_7(), "rule__Expression__Group_7__0");
					put(grammarAccess.getExpressionAccess().getGroup_8(), "rule__Expression__Group_8__0");
					put(grammarAccess.getExpressionAccess().getGroup_9(), "rule__Expression__Group_9__0");
					put(grammarAccess.getExpression_auxAccess().getGroup_0(), "rule__Expression_aux__Group_0__0");
					put(grammarAccess.getExpression_auxAccess().getGroup_0_0(), "rule__Expression_aux__Group_0_0__0");
					put(grammarAccess.getExpression_auxAccess().getGroup_1(), "rule__Expression_aux__Group_1__0");
					put(grammarAccess.getExpression_auxAccess().getGroup_1_0(), "rule__Expression_aux__Group_1_0__0");
					put(grammarAccess.getExpression_auxAccess().getGroup_2(), "rule__Expression_aux__Group_2__0");
					put(grammarAccess.getExpression_auxAccess().getGroup_2_0(), "rule__Expression_aux__Group_2_0__0");
					put(grammarAccess.getExpression_auxAccess().getGroup_3(), "rule__Expression_aux__Group_3__0");
					put(grammarAccess.getExpression_auxAccess().getGroup_3_0(), "rule__Expression_aux__Group_3_0__0");
					put(grammarAccess.getExpression_auxAccess().getGroup_4(), "rule__Expression_aux__Group_4__0");
					put(grammarAccess.getExpression_auxAccess().getGroup_4_0(), "rule__Expression_aux__Group_4_0__0");
					put(grammarAccess.getExpression_auxAccess().getGroup_5(), "rule__Expression_aux__Group_5__0");
					put(grammarAccess.getExpression_auxAccess().getGroup_6(), "rule__Expression_aux__Group_6__0");
					put(grammarAccess.getExpression_auxAccess().getGroup_7(), "rule__Expression_aux__Group_7__0");
					put(grammarAccess.getExpression_auxAccess().getGroup_8(), "rule__Expression_aux__Group_8__0");
					put(grammarAccess.getExpression_auxAccess().getGroup_9(), "rule__Expression_aux__Group_9__0");
					put(grammarAccess.getExpression_auxAccess().getGroup_10(), "rule__Expression_aux__Group_10__0");
					put(grammarAccess.getExpression_auxAccess().getGroup_11(), "rule__Expression_aux__Group_11__0");
					put(grammarAccess.getExpression_auxAccess().getGroup_12(), "rule__Expression_aux__Group_12__0");
					put(grammarAccess.getAmpersand_RuleAccess().getGroup(), "rule__Ampersand_Rule__Group__0");
					put(grammarAccess.getFloat_LiteralAccess().getGroup(), "rule__Float_Literal__Group__0");
					put(grammarAccess.getLiteral_ExpressionAccess().getGroup_0_0(), "rule__Literal_Expression__Group_0_0__0");
					put(grammarAccess.getLiteral_ExpressionAccess().getGroup_0_1(), "rule__Literal_Expression__Group_0_1__0");
					put(grammarAccess.getCreating_ExpressionAccess().getGroup(), "rule__Creating_Expression__Group__0");
					put(grammarAccess.getCreating_ExpressionAccess().getGroup_1_0(), "rule__Creating_Expression__Group_1_0__0");
					put(grammarAccess.getCreating_ExpressionAccess().getGroup_1_1(), "rule__Creating_Expression__Group_1_1__0");
					put(grammarAccess.getCreating_ExpressionAccess().getGroup_1_1_1_0(), "rule__Creating_Expression__Group_1_1_1_0__0");
					put(grammarAccess.getCreating_ExpressionAccess().getGroup_1_1_2_0(), "rule__Creating_Expression__Group_1_1_2_0__0");
					put(grammarAccess.getCreating_ExpressionAccess().getGroup_1_2(), "rule__Creating_Expression__Group_1_2__0");
					put(grammarAccess.getCast_ExpressionAccess().getGroup(), "rule__Cast_Expression__Group__0");
					put(grammarAccess.getBit_Expression_NRAccess().getGroup(), "rule__Bit_Expression_NR__Group__0");
					put(grammarAccess.getLogical_Expression_NRAccess().getGroup_0(), "rule__Logical_Expression_NR__Group_0__0");
					put(grammarAccess.getLogical_Expression_NRAccess().getGroup_0_1_1(), "rule__Logical_Expression_NR__Group_0_1_1__0");
					put(grammarAccess.getLogical_Expression_NRAccess().getGroup_1(), "rule__Logical_Expression_NR__Group_1__0");
					put(grammarAccess.getArg_ListAccess().getGroup(), "rule__Arg_List__Group__0");
					put(grammarAccess.getArg_ListAccess().getGroup_1(), "rule__Arg_List__Group_1__0");
					put(grammarAccess.getNumeric_Expression_NRAccess().getGroup(), "rule__Numeric_Expression_NR__Group__0");
					put(grammarAccess.getSwitch_statementAccess().getGroup(), "rule__Switch_statement__Group__0");
					put(grammarAccess.getSwitch_statementAccess().getGroup_6_0(), "rule__Switch_statement__Group_6_0__0");
					put(grammarAccess.getSwitch_statementAccess().getGroup_6_1(), "rule__Switch_statement__Group_6_1__0");
					put(grammarAccess.getWhile_StatementAccess().getGroup(), "rule__While_Statement__Group__0");
					put(grammarAccess.getDo_StatementAccess().getGroup(), "rule__Do_Statement__Group__0");
					put(grammarAccess.getIf_statementAccess().getGroup(), "rule__If_statement__Group__0");
					put(grammarAccess.getIf_statementAccess().getGroup_5(), "rule__If_statement__Group_5__0");
					put(grammarAccess.getTry_statementAccess().getGroup(), "rule__Try_statement__Group__0");
					put(grammarAccess.getTry_statementAccess().getGroup_2(), "rule__Try_statement__Group_2__0");
					put(grammarAccess.getTry_statementAccess().getGroup_3(), "rule__Try_statement__Group_3__0");
					put(grammarAccess.getImport_statementAccess().getGroup(), "rule__Import_statement__Group__0");
					put(grammarAccess.getImport_statementAccess().getGroup_1_0(), "rule__Import_statement__Group_1_0__0");
					put(grammarAccess.getImport_statementAccess().getGroup_1_1(), "rule__Import_statement__Group_1_1__0");
					put(grammarAccess.getPackage_statementAccess().getGroup(), "rule__Package_statement__Group__0");
					put(grammarAccess.getPackage_nameAccess().getGroup(), "rule__Package_name__Group__0");
					put(grammarAccess.getPackage_name_lineAccess().getGroup(), "rule__Package_name_line__Group__0");
					put(grammarAccess.getEXPOENT_PARTAccess().getGroup(), "rule__EXPOENT_PART__Group__0");
					put(grammarAccess.getModelAccess().getGreetingsAssignment(), "rule__Model__GreetingsAssignment");
					put(grammarAccess.getCompilation_unitAccess().getNameAssignment_1(), "rule__Compilation_unit__NameAssignment_1");
					put(grammarAccess.getCompilation_unitAccess().getImportsAssignment_2(), "rule__Compilation_unit__ImportsAssignment_2");
					put(grammarAccess.getCompilation_unitAccess().getTypeDeclarationsAssignment_3(), "rule__Compilation_unit__TypeDeclarationsAssignment_3");
					put(grammarAccess.getType_declarationAccess().getCommentAssignment_0(), "rule__Type_declaration__CommentAssignment_0");
					put(grammarAccess.getType_declarationAccess().getClassDecAssignment_1_0(), "rule__Type_declaration__ClassDecAssignment_1_0");
					put(grammarAccess.getType_declarationAccess().getInterfaceDecAssignment_1_1(), "rule__Type_declaration__InterfaceDecAssignment_1_1");
					put(grammarAccess.getInterface_declarationAccess().getModifiersAssignment_0(), "rule__Interface_declaration__ModifiersAssignment_0");
					put(grammarAccess.getInterface_declarationAccess().getInterfaceNameAssignment_2(), "rule__Interface_declaration__InterfaceNameAssignment_2");
					put(grammarAccess.getInterface_declarationAccess().getInterfaceHerdadaAssignment_3_1(), "rule__Interface_declaration__InterfaceHerdadaAssignment_3_1");
					put(grammarAccess.getInterface_declarationAccess().getInterfacesHerdadasAssignment_3_2_1(), "rule__Interface_declaration__InterfacesHerdadasAssignment_3_2_1");
					put(grammarAccess.getInterface_declarationAccess().getFieldsDeclarationAssignment_5(), "rule__Interface_declaration__FieldsDeclarationAssignment_5");
					put(grammarAccess.getClass_declarationAccess().getModifiersAssignment_0(), "rule__Class_declaration__ModifiersAssignment_0");
					put(grammarAccess.getClass_declarationAccess().getClassNameAssignment_2(), "rule__Class_declaration__ClassNameAssignment_2");
					put(grammarAccess.getClass_declarationAccess().getClassHerdadaAssignment_3_1(), "rule__Class_declaration__ClassHerdadaAssignment_3_1");
					put(grammarAccess.getClass_declarationAccess().getInterfaceImplementadaAssignment_4_1(), "rule__Class_declaration__InterfaceImplementadaAssignment_4_1");
					put(grammarAccess.getClass_declarationAccess().getInterfacesImplementadasAssignment_4_2_1(), "rule__Class_declaration__InterfacesImplementadasAssignment_4_2_1");
					put(grammarAccess.getClass_declarationAccess().getFieldsDeclarationAssignment_6(), "rule__Class_declaration__FieldsDeclarationAssignment_6");
					put(grammarAccess.getField_declarationAccess().getCommentAssignment_0_0(), "rule__Field_declaration__CommentAssignment_0_0");
					put(grammarAccess.getField_declarationAccess().getVariableDeclarationAssignment_0_1_0(), "rule__Field_declaration__VariableDeclarationAssignment_0_1_0");
					put(grammarAccess.getField_declarationAccess().getContructorNameAssignment_0_1_1(), "rule__Field_declaration__ContructorNameAssignment_0_1_1");
					put(grammarAccess.getField_declarationAccess().getMethodNameAssignment_0_1_2(), "rule__Field_declaration__MethodNameAssignment_0_1_2");
					put(grammarAccess.getField_declarationAccess().getStaticinitializerAssignment_1(), "rule__Field_declaration__StaticinitializerAssignment_1");
					put(grammarAccess.getMethod_declarationAccess().getModifiersMethodAssignment_0(), "rule__Method_declaration__ModifiersMethodAssignment_0");
					put(grammarAccess.getMethod_declarationAccess().getTypeMethodAssignment_1(), "rule__Method_declaration__TypeMethodAssignment_1");
					put(grammarAccess.getMethod_declarationAccess().getNameMethodAssignment_2(), "rule__Method_declaration__NameMethodAssignment_2");
					put(grammarAccess.getMethod_declarationAccess().getLParenAssignment_3(), "rule__Method_declaration__LParenAssignment_3");
					put(grammarAccess.getMethod_declarationAccess().getParameterListMethodAssignment_4(), "rule__Method_declaration__ParameterListMethodAssignment_4");
					put(grammarAccess.getMethod_declarationAccess().getRparentAssignment_5(), "rule__Method_declaration__RparentAssignment_5");
					put(grammarAccess.getMethod_declarationAccess().getStatementMethodAssignment_7_0(), "rule__Method_declaration__StatementMethodAssignment_7_0");
					put(grammarAccess.getMethod_declarationAccess().getDebugAssignment_7_1(), "rule__Method_declaration__DebugAssignment_7_1");
					put(grammarAccess.getConstructor_declarationAccess().getModifiersConstructorAssignment_0(), "rule__Constructor_declaration__ModifiersConstructorAssignment_0");
					put(grammarAccess.getConstructor_declarationAccess().getNameConstructorAssignment_1(), "rule__Constructor_declaration__NameConstructorAssignment_1");
					put(grammarAccess.getConstructor_declarationAccess().getLParenAssignment_2(), "rule__Constructor_declaration__LParenAssignment_2");
					put(grammarAccess.getConstructor_declarationAccess().getParameterListConstructorAssignment_3(), "rule__Constructor_declaration__ParameterListConstructorAssignment_3");
					put(grammarAccess.getConstructor_declarationAccess().getRparentAssignment_4(), "rule__Constructor_declaration__RparentAssignment_4");
					put(grammarAccess.getConstructor_declarationAccess().getStatementConstructorAssignment_5(), "rule__Constructor_declaration__StatementConstructorAssignment_5");
					put(grammarAccess.getParameter_listAccess().getParameterAssignment_0(), "rule__Parameter_list__ParameterAssignment_0");
					put(grammarAccess.getParameter_listAccess().getParametersAssignment_1_1(), "rule__Parameter_list__ParametersAssignment_1_1");
					put(grammarAccess.getParameterAccess().getTypeAssignment_0(), "rule__Parameter__TypeAssignment_0");
					put(grammarAccess.getParameterAccess().getParameterNameAssignment_1(), "rule__Parameter__ParameterNameAssignment_1");
					put(grammarAccess.getVariable_declarationAccess().getModifiersVariableAssignment_0(), "rule__Variable_declaration__ModifiersVariableAssignment_0");
					put(grammarAccess.getVariable_declarationAccess().getTypeAssignment_1(), "rule__Variable_declaration__TypeAssignment_1");
					put(grammarAccess.getVariable_declarationAccess().getNameVariableAssignment_2(), "rule__Variable_declaration__NameVariableAssignment_2");
					put(grammarAccess.getVariable_declarationAccess().getNamesAssignment_3_1(), "rule__Variable_declaration__NamesAssignment_3_1");
					put(grammarAccess.getVariable_declaratorAccess().getNameVariableAssignment_0(), "rule__Variable_declarator__NameVariableAssignment_0");
					put(grammarAccess.getVariable_declaratorAccess().getLenVectorAssignment_1_0_0(), "rule__Variable_declarator__LenVectorAssignment_1_0_0");
					put(grammarAccess.getVariable_declaratorAccess().getLenVectorAssignment_1_1(), "rule__Variable_declarator__LenVectorAssignment_1_1");
					put(grammarAccess.getVariable_declaratorAccess().getVariAssignment_2_1(), "rule__Variable_declarator__VariAssignment_2_1");
					put(grammarAccess.getVariable_initializerAccess().getArray_initAssignment_0(), "rule__Variable_initializer__Array_initAssignment_0");
					put(grammarAccess.getVariable_initializerAccess().getExpressionAssignment_1(), "rule__Variable_initializer__ExpressionAssignment_1");
					put(grammarAccess.getArray_initializerAccess().getVariableinitializerAssignment_2_0(), "rule__Array_initializer__VariableinitializerAssignment_2_0");
					put(grammarAccess.getArray_initializerAccess().getVariableinitializerAssignment_2_1_1(), "rule__Array_initializer__VariableinitializerAssignment_2_1_1");
					put(grammarAccess.getTypeAccess().getTypeSpecifierAssignment_0(), "rule__Type__TypeSpecifierAssignment_0");
					put(grammarAccess.getTypeAccess().getTypeVectorAssignment_1(), "rule__Type__TypeVectorAssignment_1");
					put(grammarAccess.getType_specifierAccess().getPrimitiveTypeAssignment_0(), "rule__Type_specifier__PrimitiveTypeAssignment_0");
					put(grammarAccess.getType_specifierAccess().getClassNameAssignment_1(), "rule__Type_specifier__ClassNameAssignment_1");
					put(grammarAccess.getStatic_initializerAccess().getStaticAssignment_0(), "rule__Static_initializer__StaticAssignment_0");
					put(grammarAccess.getStatic_initializerAccess().getNameAssignment_1(), "rule__Static_initializer__NameAssignment_1");
					put(grammarAccess.getStatement_blockAccess().getRCurlyAssignment_1(), "rule__Statement_block__RCurlyAssignment_1");
					put(grammarAccess.getStatement_blockAccess().getStatmentsAssignment_2(), "rule__Statement_block__StatmentsAssignment_2");
					put(grammarAccess.getStatement_blockAccess().getLCurlyAssignment_3(), "rule__Statement_block__LCurlyAssignment_3");
					put(grammarAccess.getStatementAccess().getVariableDeclarationAssignment_0(), "rule__Statement__VariableDeclarationAssignment_0");
					put(grammarAccess.getStatementAccess().getExpressionStatementAssignment_1_0(), "rule__Statement__ExpressionStatementAssignment_1_0");
					put(grammarAccess.getStatementAccess().getGAssignment_1_1(), "rule__Statement__GAssignment_1_1");
					put(grammarAccess.getStatementAccess().getIfStatementAssignment_2(), "rule__Statement__IfStatementAssignment_2");
					put(grammarAccess.getStatementAccess().getDoStatementAssignment_3(), "rule__Statement__DoStatementAssignment_3");
					put(grammarAccess.getStatementAccess().getWhileStatementAssignment_4(), "rule__Statement__WhileStatementAssignment_4");
					put(grammarAccess.getStatementAccess().getForStatementAssignment_5(), "rule__Statement__ForStatementAssignment_5");
					put(grammarAccess.getStatementAccess().getSwitchStatementAssignment_6(), "rule__Statement__SwitchStatementAssignment_6");
					put(grammarAccess.getStatementAccess().getExpressionAssignment_7_1(), "rule__Statement__ExpressionAssignment_7_1");
					put(grammarAccess.getStatementAccess().getRparentAssignment_7_2(), "rule__Statement__RparentAssignment_7_2");
					put(grammarAccess.getStatementAccess().getSyncStatementAssignment_7_3(), "rule__Statement__SyncStatementAssignment_7_3");
					put(grammarAccess.getStatementAccess().getRetAssignment_8_1(), "rule__Statement__RetAssignment_8_1");
					put(grammarAccess.getStatementAccess().getExpressionAssignment_8_2(), "rule__Statement__ExpressionAssignment_8_2");
					put(grammarAccess.getStatementAccess().getExpressionAssignment_9_2(), "rule__Statement__ExpressionAssignment_9_2");
					put(grammarAccess.getStatementAccess().getStatementBlockAssignment_10(), "rule__Statement__StatementBlockAssignment_10");
					put(grammarAccess.getStatementAccess().getTryStatementAssignment_11(), "rule__Statement__TryStatementAssignment_11");
					put(grammarAccess.getStatementAccess().getNameStatementAssignment_12_0(), "rule__Statement__NameStatementAssignment_12_0");
					put(grammarAccess.getStatementAccess().getStatementAssignment_12_2(), "rule__Statement__StatementAssignment_12_2");
					put(grammarAccess.getStatementAccess().getNameAssignment_13_2(), "rule__Statement__NameAssignment_13_2");
					put(grammarAccess.getStatementAccess().getNameAssignment_14_2(), "rule__Statement__NameAssignment_14_2");
					put(grammarAccess.getFor_StatementAccess().getVariableAssignment_2_0(), "rule__For_Statement__VariableAssignment_2_0");
					put(grammarAccess.getFor_StatementAccess().getExpressionAssignment_2_2_0(), "rule__For_Statement__ExpressionAssignment_2_2_0");
					put(grammarAccess.getFor_StatementAccess().getExpression2Assignment_3(), "rule__For_Statement__Expression2Assignment_3");
					put(grammarAccess.getFor_StatementAccess().getExpression3Assignment_5(), "rule__For_Statement__Expression3Assignment_5");
					put(grammarAccess.getFor_StatementAccess().getStatementAssignment_7(), "rule__For_Statement__StatementAssignment_7");
					put(grammarAccess.getExpressionAccess().getNumericExpression3Assignment_0_0_0(), "rule__Expression__NumericExpression3Assignment_0_0_0");
					put(grammarAccess.getExpressionAccess().getAuxAssignment_0_1(), "rule__Expression__AuxAssignment_0_1");
					put(grammarAccess.getExpressionAccess().getLogicalExpressionAssignment_1_0(), "rule__Expression__LogicalExpressionAssignment_1_0");
					put(grammarAccess.getExpressionAccess().getAuxAssignment_1_1(), "rule__Expression__AuxAssignment_1_1");
					put(grammarAccess.getExpressionAccess().getBitExpressionAssignment_2_0(), "rule__Expression__BitExpressionAssignment_2_0");
					put(grammarAccess.getExpressionAccess().getAuxAssignment_2_1(), "rule__Expression__AuxAssignment_2_1");
					put(grammarAccess.getExpressionAccess().getCastExpressionAssignment_3_0_0(), "rule__Expression__CastExpressionAssignment_3_0_0");
					put(grammarAccess.getExpressionAccess().getAuxAssignment_3_1(), "rule__Expression__AuxAssignment_3_1");
					put(grammarAccess.getExpressionAccess().getCreatingExpressionAssignment_4_0_0(), "rule__Expression__CreatingExpressionAssignment_4_0_0");
					put(grammarAccess.getExpressionAccess().getAuxAssignment_4_1(), "rule__Expression__AuxAssignment_4_1");
					put(grammarAccess.getExpressionAccess().getLiteralExpressionAssignment_5_0(), "rule__Expression__LiteralExpressionAssignment_5_0");
					put(grammarAccess.getExpressionAccess().getAuxAssignment_5_1(), "rule__Expression__AuxAssignment_5_1");
					put(grammarAccess.getExpressionAccess().getNullAssignment_6_0(), "rule__Expression__NullAssignment_6_0");
					put(grammarAccess.getExpressionAccess().getAuxAssignment_6_1(), "rule__Expression__AuxAssignment_6_1");
					put(grammarAccess.getExpressionAccess().getSuperAssignment_7_0(), "rule__Expression__SuperAssignment_7_0");
					put(grammarAccess.getExpressionAccess().getAuxAssignment_7_1(), "rule__Expression__AuxAssignment_7_1");
					put(grammarAccess.getExpressionAccess().getThisAssignment_8_0(), "rule__Expression__ThisAssignment_8_0");
					put(grammarAccess.getExpressionAccess().getAuxAssignment_8_1(), "rule__Expression__AuxAssignment_8_1");
					put(grammarAccess.getExpressionAccess().getNameAssignment_9_0(), "rule__Expression__NameAssignment_9_0");
					put(grammarAccess.getExpressionAccess().getAuxAssignment_9_1(), "rule__Expression__AuxAssignment_9_1");
					put(grammarAccess.getExpression_auxAccess().getArgListAssignment_0_0_1(), "rule__Expression_aux__ArgListAssignment_0_0_1");
					put(grammarAccess.getExpression_auxAccess().getAuxAssignment_0_1(), "rule__Expression_aux__AuxAssignment_0_1");
					put(grammarAccess.getExpression_auxAccess().getExpression2Assignment_1_0_1(), "rule__Expression_aux__Expression2Assignment_1_0_1");
					put(grammarAccess.getExpression_auxAccess().getAuxAssignment_1_1(), "rule__Expression_aux__AuxAssignment_1_1");
					put(grammarAccess.getExpression_auxAccess().getExpression2Assignment_2_0_1(), "rule__Expression_aux__Expression2Assignment_2_0_1");
					put(grammarAccess.getExpression_auxAccess().getAuxAssignment_2_1(), "rule__Expression_aux__AuxAssignment_2_1");
					put(grammarAccess.getExpression_auxAccess().getExpressionCommaAssignment_3_0_1(), "rule__Expression_aux__ExpressionCommaAssignment_3_0_1");
					put(grammarAccess.getExpression_auxAccess().getAuxAssignment_3_1(), "rule__Expression_aux__AuxAssignment_3_1");
					put(grammarAccess.getExpression_auxAccess().getNameAssignment_4_0_1(), "rule__Expression_aux__NameAssignment_4_0_1");
					put(grammarAccess.getExpression_auxAccess().getAuxAssignment_4_1(), "rule__Expression_aux__AuxAssignment_4_1");
					put(grammarAccess.getExpression_auxAccess().getSginAssignment_5_0(), "rule__Expression_aux__SginAssignment_5_0");
					put(grammarAccess.getExpression_auxAccess().getAuxAssignment_5_1(), "rule__Expression_aux__AuxAssignment_5_1");
					put(grammarAccess.getExpression_auxAccess().getNumericSignAssignment_6_0(), "rule__Expression_aux__NumericSignAssignment_6_0");
					put(grammarAccess.getExpression_auxAccess().getExp2Assignment_6_1(), "rule__Expression_aux__Exp2Assignment_6_1");
					put(grammarAccess.getExpression_auxAccess().getAuxAssignment_6_2(), "rule__Expression_aux__AuxAssignment_6_2");
					put(grammarAccess.getExpression_auxAccess().getTestingSignAssignment_7_0(), "rule__Expression_aux__TestingSignAssignment_7_0");
					put(grammarAccess.getExpression_auxAccess().getExp1Assignment_7_1(), "rule__Expression_aux__Exp1Assignment_7_1");
					put(grammarAccess.getExpression_auxAccess().getAuxAssignment_7_2(), "rule__Expression_aux__AuxAssignment_7_2");
					put(grammarAccess.getExpression_auxAccess().getLogicalSignAssignment_8_0_0(), "rule__Expression_aux__LogicalSignAssignment_8_0_0");
					put(grammarAccess.getExpression_auxAccess().getAmpersandAssignment_8_0_1(), "rule__Expression_aux__AmpersandAssignment_8_0_1");
					put(grammarAccess.getExpression_auxAccess().getExp1Assignment_8_1(), "rule__Expression_aux__Exp1Assignment_8_1");
					put(grammarAccess.getExpression_auxAccess().getAuxAssignment_8_2(), "rule__Expression_aux__AuxAssignment_8_2");
					put(grammarAccess.getExpression_auxAccess().getExp1Assignment_9_1(), "rule__Expression_aux__Exp1Assignment_9_1");
					put(grammarAccess.getExpression_auxAccess().getExp2Assignment_9_3(), "rule__Expression_aux__Exp2Assignment_9_3");
					put(grammarAccess.getExpression_auxAccess().getAuxAssignment_9_4(), "rule__Expression_aux__AuxAssignment_9_4");
					put(grammarAccess.getExpression_auxAccess().getStringSignAssignment_10_0(), "rule__Expression_aux__StringSignAssignment_10_0");
					put(grammarAccess.getExpression_auxAccess().getExp1Assignment_10_1(), "rule__Expression_aux__Exp1Assignment_10_1");
					put(grammarAccess.getExpression_auxAccess().getAuxAssignment_10_2(), "rule__Expression_aux__AuxAssignment_10_2");
					put(grammarAccess.getExpression_auxAccess().getBitSignAssignment_11_0(), "rule__Expression_aux__BitSignAssignment_11_0");
					put(grammarAccess.getExpression_auxAccess().getExpressionBitAssignment_11_1(), "rule__Expression_aux__ExpressionBitAssignment_11_1");
					put(grammarAccess.getExpression_auxAccess().getAuxAssignment_11_2(), "rule__Expression_aux__AuxAssignment_11_2");
					put(grammarAccess.getExpression_auxAccess().getLogicOpAssignment_12_0(), "rule__Expression_aux__LogicOpAssignment_12_0");
					put(grammarAccess.getExpression_auxAccess().getLogicExpAssignment_12_1(), "rule__Expression_aux__LogicExpAssignment_12_1");
					put(grammarAccess.getAmpersand_RuleAccess().getA1Assignment_0(), "rule__Ampersand_Rule__A1Assignment_0");
					put(grammarAccess.getAmpersand_RuleAccess().getA2Assignment_1_0(), "rule__Ampersand_Rule__A2Assignment_1_0");
					put(grammarAccess.getFloat_LiteralAccess().getDecimalDigits1Assignment_0(), "rule__Float_Literal__DecimalDigits1Assignment_0");
					put(grammarAccess.getFloat_LiteralAccess().getDecimalDigits2Assignment_2(), "rule__Float_Literal__DecimalDigits2Assignment_2");
					put(grammarAccess.getFloat_LiteralAccess().getExpAssignment_3(), "rule__Float_Literal__ExpAssignment_3");
					put(grammarAccess.getFloat_LiteralAccess().getFloatTypeSufixAssignment_4(), "rule__Float_Literal__FloatTypeSufixAssignment_4");
					put(grammarAccess.getLiteral_ExpressionAccess().getExpAssignment_0_0_0(), "rule__Literal_Expression__ExpAssignment_0_0_0");
					put(grammarAccess.getLiteral_ExpressionAccess().getExp1Assignment_0_1_0(), "rule__Literal_Expression__Exp1Assignment_0_1_0");
					put(grammarAccess.getLiteral_ExpressionAccess().getExp2Assignment_1(), "rule__Literal_Expression__Exp2Assignment_1");
					put(grammarAccess.getLiteral_ExpressionAccess().getStringAssignment_2(), "rule__Literal_Expression__StringAssignment_2");
					put(grammarAccess.getLiteral_ExpressionAccess().getCharLitAssignment_3(), "rule__Literal_Expression__CharLitAssignment_3");
					put(grammarAccess.getCreating_ExpressionAccess().getClassNameAssignment_1_0_0(), "rule__Creating_Expression__ClassNameAssignment_1_0_0");
					put(grammarAccess.getCreating_ExpressionAccess().getArgListAssignment_1_0_2(), "rule__Creating_Expression__ArgListAssignment_1_0_2");
					put(grammarAccess.getCreating_ExpressionAccess().getTypeSpecifierAssignment_1_1_0(), "rule__Creating_Expression__TypeSpecifierAssignment_1_1_0");
					put(grammarAccess.getCreating_ExpressionAccess().getExpressionAssignment_1_1_1_0_1(), "rule__Creating_Expression__ExpressionAssignment_1_1_1_0_1");
					put(grammarAccess.getCreating_ExpressionAccess().getExpressionAssignment_1_2_1(), "rule__Creating_Expression__ExpressionAssignment_1_2_1");
					put(grammarAccess.getCast_ExpressionAccess().getTypeAssignment_1(), "rule__Cast_Expression__TypeAssignment_1");
					put(grammarAccess.getCast_ExpressionAccess().getExpressionAssignment_3(), "rule__Cast_Expression__ExpressionAssignment_3");
					put(grammarAccess.getBit_Expression_NRAccess().getExpressionAssignment_1(), "rule__Bit_Expression_NR__ExpressionAssignment_1");
					put(grammarAccess.getLogical_Expression_NRAccess().getExclamationAssignment_0_0(), "rule__Logical_Expression_NR__ExclamationAssignment_0_0");
					put(grammarAccess.getLogical_Expression_NRAccess().getExpressionAssignment_0_1_0(), "rule__Logical_Expression_NR__ExpressionAssignment_0_1_0");
					put(grammarAccess.getLogical_Expression_NRAccess().getExpressionAssignment_0_1_1_1(), "rule__Logical_Expression_NR__ExpressionAssignment_0_1_1_1");
					put(grammarAccess.getLogical_Expression_NRAccess().getExpressionAssignment_1_1(), "rule__Logical_Expression_NR__ExpressionAssignment_1_1");
					put(grammarAccess.getLogical_Expression_NRAccess().getTrueAssignment_2(), "rule__Logical_Expression_NR__TrueAssignment_2");
					put(grammarAccess.getLogical_Expression_NRAccess().getFalseAssignment_3(), "rule__Logical_Expression_NR__FalseAssignment_3");
					put(grammarAccess.getArg_ListAccess().getExpressionAssignment_0(), "rule__Arg_List__ExpressionAssignment_0");
					put(grammarAccess.getArg_ListAccess().getExpressionsAssignment_1_1(), "rule__Arg_List__ExpressionsAssignment_1_1");
					put(grammarAccess.getNumeric_Expression_NRAccess().getSinal_numericAssignment_0(), "rule__Numeric_Expression_NR__Sinal_numericAssignment_0");
					put(grammarAccess.getNumeric_Expression_NRAccess().getExpressionAssignment_1(), "rule__Numeric_Expression_NR__ExpressionAssignment_1");
					put(grammarAccess.getSwitch_statementAccess().getLParenAssignment_2(), "rule__Switch_statement__LParenAssignment_2");
					put(grammarAccess.getSwitch_statementAccess().getExpressionAssignment_3(), "rule__Switch_statement__ExpressionAssignment_3");
					put(grammarAccess.getSwitch_statementAccess().getRparentAssignment_4(), "rule__Switch_statement__RparentAssignment_4");
					put(grammarAccess.getSwitch_statementAccess().getExpression2Assignment_6_0_1(), "rule__Switch_statement__Expression2Assignment_6_0_1");
					put(grammarAccess.getSwitch_statementAccess().getSwitchStatementsAssignment_6_2(), "rule__Switch_statement__SwitchStatementsAssignment_6_2");
					put(grammarAccess.getWhile_StatementAccess().getExpressionAssignment_1(), "rule__While_Statement__ExpressionAssignment_1");
					put(grammarAccess.getWhile_StatementAccess().getRparentAssignment_2(), "rule__While_Statement__RparentAssignment_2");
					put(grammarAccess.getWhile_StatementAccess().getWhileStatementAssignment_3(), "rule__While_Statement__WhileStatementAssignment_3");
					put(grammarAccess.getDo_StatementAccess().getDoStatementAssignment_1(), "rule__Do_Statement__DoStatementAssignment_1");
					put(grammarAccess.getDo_StatementAccess().getLparentAssignment_3(), "rule__Do_Statement__LparentAssignment_3");
					put(grammarAccess.getDo_StatementAccess().getRparentAssignment_4(), "rule__Do_Statement__RparentAssignment_4");
					put(grammarAccess.getIf_statementAccess().getLparenAssignment_1(), "rule__If_statement__LparenAssignment_1");
					put(grammarAccess.getIf_statementAccess().getExpressionAssignment_2(), "rule__If_statement__ExpressionAssignment_2");
					put(grammarAccess.getIf_statementAccess().getRparentAssignment_3(), "rule__If_statement__RparentAssignment_3");
					put(grammarAccess.getIf_statementAccess().getIdStatementAssignment_4(), "rule__If_statement__IdStatementAssignment_4");
					put(grammarAccess.getIf_statementAccess().getElseStatementAssignment_5_1(), "rule__If_statement__ElseStatementAssignment_5_1");
					put(grammarAccess.getTry_statementAccess().getTryStatementAssignment_1(), "rule__Try_statement__TryStatementAssignment_1");
					put(grammarAccess.getTry_statementAccess().getLParenAssignment_2_1(), "rule__Try_statement__LParenAssignment_2_1");
					put(grammarAccess.getTry_statementAccess().getParametersAssignment_2_2(), "rule__Try_statement__ParametersAssignment_2_2");
					put(grammarAccess.getTry_statementAccess().getRparentAssignment_2_3(), "rule__Try_statement__RparentAssignment_2_3");
					put(grammarAccess.getTry_statementAccess().getCatchStatementAssignment_2_4(), "rule__Try_statement__CatchStatementAssignment_2_4");
					put(grammarAccess.getTry_statementAccess().getFinallyStatementAssignment_3_1(), "rule__Try_statement__FinallyStatementAssignment_3_1");
					put(grammarAccess.getImport_statementAccess().getClassNameAssignment_1_0_0(), "rule__Import_statement__ClassNameAssignment_1_0_0");
					put(grammarAccess.getImport_statementAccess().getPacNameAssignment_1_1_0(), "rule__Import_statement__PacNameAssignment_1_1_0");
					put(grammarAccess.getPackage_statementAccess().getPacNameAssignment_1(), "rule__Package_statement__PacNameAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser typedParser = (org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
